# Generated by Django 5.2.13 on 2026-05-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='user',
        ),
        migrations.AddField(
            model_name='cropdata',
            name='result',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
